server:
  servlet:
    context-path: /
  port: 1234

spring:
  application:
    name: TestSpringSecurity
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=java5_foodmart;encrypt=false;trustServerCertificate=True
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

